### ISSUE TITLE
feature request: allow modify shortcuts

### ISSUE THREAD

**Issue by HowcanoeWang** [darkstego/Mudeer#15]
Thanks first for making such a useful tool for the KDE

Currently, some shortcuts conflict with the system's native shortcuts, e.g. Meta + D (Win + D) = show desktop, which is already a familiar operation for users from Windows.

The readme mentioned we can check out the conflict shortcut in the system setting, but instead of modify some commonly used shortcut, will it possible to DIY the shortcut for this plugin?

For example, I also use the Rectange App on Mac, which provides the DIY function, it would be great that I can keep consistent between my different devices

![](https://rectangleapp.com/assets/images/shortcutScreenshot.jpg)

**Comment by darkstego** [comment]
Yes, the shortcuts are fully customizable. Just go to System Setting -> Shortcuts. There type in "mudeer" in the search to see all the shortcuts. You can choose whatever you want, and you don't have to implement all of them if you don't want to.

The ones I show by default are just my suggestions, because I feel they work well.

**Comment by HowcanoeWang** [comment]
Thanks for this reply, I have realized it needs to be changed in the system setting rather than the plugin configuration. 

(it would be better to highlight this point in the readme, I apologize for missing it when read through)
