### ISSUE TITLE
Unable to use dual full screen

### ISSUE THREAD

**Issue by scshafe** [darkstego/Mudeer#19]
Perhaps I'm just misunderstanding how I'm supposed to use the split full-screen or maybe I'm misundertanding the functionality itself.  I should note I'm just using a regular size screen, I'm not sure if that should make a difference.

I'd like to watch a video in full screen mode on half my screen, while have a note taking application open on the other half.  It doesn't matter to me if the note taking application is in full screen mode or simply occupies the rest of the screen in the normal window.

I have no other shortcuts set to meta+ctrl+shift+f, but I am unable to get a full screen application to use just half the screen as shown in the gif on the homepage.

I'm trying the following 2 ways: 1 starting with the video window simply in focus and the other with it already in full screen mode (taking up the entire screen).

meta+ctrl+shift+f + side arrow
meta+ctrl+shift+f    release then meta+side arrow

same with meta+alt+shift+f

neither will make the application occupy just half the screen.

I'm running X11server on

Kubuntu 22.04
KDE Plasma Version 5.24.7
KDE Frameworks Version 5.92.0
Qt Version 5.15.3

Am I misunderstanding the functionality/usage or is this an issue?

**Comment by darkstego** [comment]
I am unsure what the arrow key shortcuts are, since they aren't part of the default shortcuts. You might be triggering KDE shortcuts rather than the Mudeer ones.

Here is how I do it:

- Run video in full screen
- Press full screen prefix (default: Super+Shift+F)
- Press shortcut of location (right half: Super+Shift+V)

Hope this helps.
